# docker-compose build devenv
# docker-compose up --no-attach devenv

version: '3.8'
services:
  devenv:
    image: zsdev-i
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: zsdev-c
    tty: true
    stdin_open: true
    attach: false
    volumes:
    - ~/.ssh:/root/.ssh
