## docker build -f devenv.Dockerfile -t zsdev:latest .
FROM archlinux:latest

## Installing dependencies; last dependencies for LSPs
RUN pacman --noconfirm -Syu  && pacman --noconfirm -S \
openssh \
git \
less \
fzf \
ripgrep \
vim \
neovim \
tmux \
mc \
clang \
nodejs \
npm

## Copy dotfiles downloaded from github
COPY . /root/dotfiles

## Deploy dotfiles and automate sourcing (interactive, tmux, git)
RUN /root/dotfiles/deploy.sh -y

# Install LSPs for webdev
RUN npm install -g \
typescript \
typescript-language-server \
@tailwindcss/language-server

WORKDIR /workspace
