## docker build -f devenv.Dockerfile -t zsdev:latest .
FROM archlinux:latest

## Installing dependencies; last dependencies for LSPs
RUN pacman --noconfirm -Syu  && pacman --noconfirm -S \
openssh \
git \
less \
fzf \
ripgrep \
vim \
neovim \
tmux \
mc \
clang \
nodejs \
npm

## Copy dotfiles downloaded from github
COPY . /root/dotfiles

## Deploy dotfiles and automate sourcing (interactive, tmux, git)
RUN /root/dotfiles/deploy.sh && \
echo 'source ~/.bash_startup' > ~/.bashrc && \
echo 'source ~/.bash_aliases' >> ~/.bashrc && \
echo 'alias dotclone="git clone --recurse-submodules --shallow-submodules git@github.com:zsidanyi/dotfiles.git ~/dotfiles"' >> ~/.bashrc && \
echo 'source ~/.bash_startup' > ~/.bash_profile && \
echo 'source ~/.bash_aliases' >> ~/.bash_profile && \
echo '[include]' >> ~/.gitconfig && \
echo '    path = ~/.gitconfig_include' >> ~/.gitconfig

# Install LSPs for webdev
RUN npm install -g \
typescript \
typescript-language-server \
@tailwindcss/language-server

WORKDIR /workspace
